export const paragraphs = [
    {
        title: '3. Obligations of the Broker',
        text: 'The Broker will perform the Services with the reasonable skill, care and diligence expected of a professional shipbroker, in the same manner as if the Broker was acting for its own account, exercising diligence to seek to comply with any applicable laws, rules and regulations including those in relation to money laundering, bribery and In dealing with others the Broker will stay within the authority given by the Client and exercise diligence to avoid During Negotiations the Broker shall pass on offers, counteroffers and other such communications accurately and in a timely manner. This obligation applies to passing communications both to and from the It is understood that the Broker may be dealing with Representatives or other intermediaries rather than directly with a In such cases the Broker is dealing with such Representatives or other intermediaries in good faith as to the authority they possess but the Broker does not give a warranty as to that authority. If the Broker is acting directly for a Principal then the Broker may warrant that it has the authority of that Principal and, where so acting for the Client, the Client hereby expressly authorises the Broker to warrant that it has the authority of the Client as The Broker will, where requested, provide information in respect of a Principal, including information regarding corporate structures or financial standing, but it is understood and agreed that where it does so, it provides such information in good faith but without It is the obligation of the Principal to decide whether to enter into a Fixture with the proposed counterparty and on what terms and, where necessary, to verify by independent means the information so provided by the Broker. Unless otherwise agreed in writing the Services are not provided on an exclusive basis and it is understood that the Broker may provide services to other parties, including in relation to the same or other Fixtures/Services. In the event the Broker is dealing directly with two or more Principals in relation to the same Fixture the Broker’s duties will be to pass on offers, counteroffers and other such communications accurately and in a timely manner as authorised by each Principal in turn.'
    },
    {
        title: '4. Confidentiality',
        text: 'Where one of the Client or the Broker (the “Receiving Party“) is given information stated by the other party (the “Other Party“) to be on a confidential basis or it is expressly agreed that a Fixture is confidential (in either case “Confidential Information“) the Receiving Party will hold that Confidential Information in confidence and will not disclose it to any other person without prior permission from the Other Party. This obligation will not however extend to information which (i) was already or becomes known to the Receiving Party through other sources not subject to such an obligation of confidentiality (ii) is or becomes known to the market generally other than as a result of a breach of this obligation or (iii) which the Receiving Party is obliged to disclose pursuant to an order of a court or other such authority. In all cases such obligation of confidentiality shall be deemed to end one (1) year after the end of performance of the Fixture/Services in question or in the absence of a concluded Fixture one (1) year from the end of the Negotiations. This clause 4shall survive termination of the Contract.'
    },
    {
        title: '5. Obligations to the Broker',
        text: 'If the Client is a Principal, it warrants that it has full legal power to enter into the Fixture brought about by the Services. If the Client is acting as a Representative, the Client warrants that it has the Principal’s authority (i) to accept these Conditions on the Principal’s behalf and (ii) to make all offers, counteroffers and representations made during Negotiations and (iii) to agree a Fixture on the Principal’s Where Broking Services are provided, the Client is deemed to have engaged the Broker in relation to any Fixture that arises in connection with those Broking Services whether or not it is concluded via the The Client will provide the Broker with all information and instructions necessary for the performance of the Services. Where actions need to be taken by a certain time (such as reply times during Negotiations) the Client will ensure that all necessary responses, information and instructions are provided by it to the Broker, within working hours in the location in which the Broker is located, in good and sufficient time to permit the Broker to forward such responses, information and instructions, and/or to take such action as may be required, prior to the relevant time limit in the time zone in which the response, information, instruction or action (as relevant) is required to be received or If the Broker has asked the Client to use specific e-mail addresses for messages then the Client undertakes to use those e-mail addresses. In the event that the Client does not receive a prompt acknowledgement of receipt of time sensitive messages from the Broker, the Client undertakes to contact the Broker to confirm that such messages have been received by the Broker. The Broker will have no responsibility for a failure to take action in relation to information or instructions contained in a message unless it is sent to the correct address and has been acknowledged as received by the The Client will take care to avoid misrepresentations occurring in The Client will carefully review all messages sent to, or copied to, the Client and promptly advise the Broker of any errors or misrepresentations. The Broker is not responsible for the consequences of a failure by the Client to review messages.',
        textExtra: 'The Client warrants that neither the Services requested nor the Fixture are unlawful and are not of a nature as could render the provision of the Services by the Broker or the conclusion or performance of the Fixture in breach of any relevant law, including (i) sanctions imposed by the United Nations, European Union, The United States of America or any national government having authority over it, the Broker Group, a Representative or a Principal (ii) laws relating to money laundering, bribery and corruption. In the event that, at any time after the request for Services to be provided by the Broker has been made by the Client or the Fixture has been concluded, the Client becomes aware that the Services or the Fixture may be unlawful or that the provision of the Services by the Broker or the performance of the Fixture may be in breach of any such relevant law, the Client undertakes to inform the Broker thereof promptly. In such event, or in the event that the Broker in its absolute discretion believes that the Services or the provision of the Services (or the Fixture or the performance of the Fixture) may infringe any such law, the Broker may by written notice terminate the provision of the Services immediately. In the event of such termination the Broker shall have no liability arising from such termination whatsoever and howsoever'
    },
    {
        title: '6. Market Reports',
        text: 'If the Broker or Broker Group publishes market reports, commentary or other catalogues, circulars or literature, these are provided for general information only and not for use in relation to specific Fixtures nor as a substitute for Other Services. Such documents do not constitute advice and nothing contained in such documents amounts to a recommendation to enter or not to enter into a Fixture or for any other purposes whatsoever and the Broker has no liability for the consequences of any person, including the Client, purporting to rely on such documents.'
    },
    {
        title: '7. The Broker’s remuneration',
        text: 'In relation to Fixtures, the Broker’s remuneration will (unless otherwise agreed) be in the form of a fee calculated on the basis of an agreed percentage of the freight, hire or purchase price as the case may be. The level of the fee payable and the party responsible for payment will be agreed in writing by the Broker with one or more of the Principals or be set out in the Negotiations and the If the fee payable to the Broker is recorded in a clause in the contract or document evidencing the Fixture then the fee will be payable in accordance with that The Broker will be deemed to have acted in reliance on the insertion of such clause and assented to the terms of the clause governing its right to fees. If the Client is the party agreed to be responsible for paying the fee, it undertakes to the Broker that it shall make the payment or payments. If the Client is not the party responsible for making payment of the fee, the Client expressly agrees to procure the payment of such fee by any relevant Principal and further to provide all necessary assistance and co-operation to the Broker in respect of its attempts to obtain the payment of such fee by the relevant Nothing in these terms will prevent, limit or restrict the Broker from enforcing a clause in respect of its fees or other clause conferring a benefit on it as a third party in accordance with the terms of the In the absence of any specific provisions to the contrary contained in the Fixture, any fee payable on voyage charters is due and payable as a percentage of sums due for deadfreight and demurrage as well as on Freight shall include all items that comprise the freight rate. On time charters, any fee will be due and payable on the hire payable under the charter throughout its duration, including any period of continuation or extension of the charter. Fees due and payable as a percentage of sums which are, as relevant, received or payable by the Client are payable as and when such sums are, as relevant, received or paid, exclusive of any right of set-off, and the Client will not withhold payment pending resolution of unconnected matters. Fees are exclusive of all taxes and duties, which will, where required, be payable in addition.',
        textExtra: 'Post Fixture Services and Other Services will be subject to the agreement of a specific fee between the Client and the Broker. The Broker will invoice the Client at the completion of the Services or at such other times and in such stages as may have been The Client will pay any fee so agreed within 30 days of the date of the invoice. If the amount of any fee and/or the manner of its payment is not specifically agreed a reasonable fee will be payable in accordance with market Where payment of the Broker’s remuneration is not made on the due date, the Broker, at its sole discretion, reserves the right to charge interest on the overdue amount at the annual rate of [three per cent (3%)] per annum above the current bank base rate accruing on a daily basis due date until the date of actual payment of the overdue amount, compounding'
    },

    {
        title: '8. Limitation of Liability',
        subTitle: 'THIS CLAUSE LIMITS THE BROKER’S LIABILITY TO THE CLIENT',
        text: 'The Broker and the Client agree that the limits and exclusions of liability found in this clause 8are fair and reasonable having regard of the nature of the Services, the fees paid for the Services by the Client and all other circumstances known to the Client and the Broker relating to the Services at the time these Conditions are Nothing in these terms and conditions limits the liability of the Broker for (i) fraud or fraudulent misrepresentation (ii) death or personal injury caused by the gross negligence of the The Broker will, subject to the provisions of this clause 8, be liable to the Client for damage directly caused by the failure to perform the Services with the reasonable skill and care expected of a professional shipbroker provided always that the Broker will not be liable for: loss of profits, loss of or interruption to business, loss of reputation and/or goodwill, loss of data, loss of use or indirect or consequential damage caused by any event or cause that the Broker was unable to avoid and/or the consequences of which could not have been prevented by the exercise by the Broker of reasonable damage which was not solely caused by the act or omission of the Broker or which would have occurred in any The total liability of the Broker arising from or in connection with the Services shall in no circumstances exceed the lower of (i) the amount of fees in fact paid to the Broker by the Client in respect of the particular Services (or, as relevant, the particular Fixture) in connection with which the claim arises or (ii) the sum of USD 1,000,000 (one million United States dollars). The exclusions and/or limitations set out in this clause shall apply whether the claim against the Broker is brought in contract, tort (including for negligence) breach of statutory duty or for any other cause.',
        textExtra: 'Any claim against the Broker must be made in writing and notified to the Broker within 14 days of the date on which the Client became aware or ought to have become aware of the circumstances giving rise to the claim and any claim not so notified shall be deemed waived and absolutely The Broker shall in any event be discharged of all liability arising out of the Services, and any claim in respect thereof shall be extinguished, unless suit is brought and served upon the Broker in accordance with clause 13 below within one (1) year of the end of performance of the Services or, if later, within one (1) year of the end of performance of the Fixture (or in the absence of a concluded Fixture within one (1) year from the end of the Negotiations).'
    },
    {
        title: '9. Termination',
        text: 'The Broker shall be entitled to terminate the Contract with immediate effect and without liability by giving written notice to the Client if: the Client commits any material breach of any term of the Contract (or, if such breach is capable of remedy, if the Client fails to remedy such breach within fourteen (14) days of receipt of a written request from the Broker ); the Client has a change of control (as control is defined by section 840 of the Income and Corporation Taxes Act 1988); or the Client calls a meeting of its creditors, makes a proposal for a voluntary arrangement, becomes subject to a voluntary arrangement, is unable to pay its debts within the meaning of section 123 of the Insolvency Act 1986, has a receiver, manager or administrative receiver appointed over any of its assets, undertaking or income, has passed a resolution for its winding-up, is subject to a petition presented to any court for its winding up, has a provisional liquidator appointed, has a proposal made for a scheme of arrangement under part 6 of the Companies Act 2006, has an administrator appointed in respect of it or is the subject of an application for administration filed at any court or a notice of intention to appoint an administrator is given by any person or is the subject of a notice to strike off the register or carries out or undertakes or is subject to or undergoes any analogous act, process or proceedings under any applicable.',
        textExtra: 'Immediately upon termination, for any cause whatsoever, the Client shall pay the Broker all fees earned and recoverable costs incurred in respect of the Services performed up to the date of the termination of the Services, together with such reasonable costs and/or expenses incurred by the Broker as a result of the termination of the Services. The Client will thereafter remain liable to pay to the Broker any fees which become due and payable after the date of termination of the Services in respect of any Fixtures which were concluded on or before the date of termination and/or which arise after the date of termination of the Services following performance of the Services prior to the date of termination of the',
    },
    {
        title: '10. Force Majeure',
        text: 'No party shall be liable to another party under this Contract for any failure to perform or delay in performance of its obligations if and in so far as and for so long as such performance is delayed or hindered by the other’s acts or omissions or for an event reasonably beyond the control of that party including wars whether or not declared, threat or preparation for war, armed conflict, imposition of sanctions, embargo, terrorist attacks, civil war, civil disturbances, riots, public disorder, acts of God including fire, flood, earthquake, windstorm or other natural disaster, epidemic or pandemic, any labour dispute including strike, lockout or industrial action (whether relating to its own employees or others), abnormally adverse weather conditions, natural disasters, destruction of machines, equipment or factories (“Force Majeure“).',
        textExtra: 'Notwithstanding clause 1,an event of Force Majeure shall not, under any circumstances, excuse a payment obligation. In the event that the circumstances constituting Force Majeure continue for an uninterrupted period of ninety (90) days, either party may terminate the Contract immediately by giving written notice to the other'
    },
    {
        title: '11. Notices',
        text: 'Any notice or other communication given to a party under or in connection with this Contract shall be in writing and shall be deemed to have been duly given if sent or delivered to the party concerned at such address as the party may from time to time notify in writing or to the correct facsimile number or electronic mail address (as notified by the parties) and shall be deemed to have been served : if sent by courier or by recorded delivery letter, upon the date of presentation of the notice at the recipient’s address if sent by ordinary post, 48 hours after posting, and in the case of a facsimile or electronic transmission, on the following day or in the case of electronic mail on the same day.'
    },
    {
        title: '12. Miscellaneous',
        text: 'All intellectual property rights in or arising out of the Contract belong to the Broker. The Broker has a general lien on all documents in its possession or control for all sums due from the Client to the Broker whether arising out of the Fixture or the Services or If a court finds that any provision of these terms and conditions is invalid, illegal or unenforceable, that provision shall, to the minimum extent required, be deemed deleted and the validity, legality and enforceability of the remainder of that and all other provisions of these terms and conditions shall not be By accepting the Services, the Client agrees to be bound by these Conditions to the exclusion of all other representations, statements, conditions, terms and warranties, whether express or implied, statutory or otherwise except any implied by law or statute which cannot be excluded by.'
    },
    {
        title: '13. Jurisdiction and Law',
        text: 'This Contract and any dispute or claim arising out of or in connection with it including its subject matter or formation (including any non-contractual obligations dispute or claims) shall be governed by and construed in accordance with the laws of England and Wales. All disputes arising out of or in connection with this Contract shall, after an attempt to resolve such disputes amicably shall have been made in good faith, be finally settled by arbitration to be held in London in accordance with the terms of the Arbitration Act 1996.',
        textExtra: 'Any arbitration shall be conducted in accordance with the London Maritime Arbitrators’ Association (LMAA) Terms current at the time when the arbitration proceedings are commenced. In cases where the value of the claim does not exceed the sum of USD 100,000 (or such other sum as the Parties may otherwise agree) the arbitration shall be conducted in accordance with the LMAA Small Claims Procedure current at the time the arbitration is commenced. The arbitral tribunal shall, unless the parties agree to the nomination of a sole arbitrator and/or to the arbitration being conducted in accordance with the LMAA Small Claims Procedure], be constituted of three arbitrators, one to be appointed by each of the Client and the Broker and the third by the two so appointed. In the event that the Client is a Representative, it is agreed that the Representative and any Principal on behalf of which it is acting shall, together, constitute the Client for the purposes of the appointment procedure.'
    }
]